### PR TITLE
preserve animated css display

### PR DESCRIPTION
**Pull request by lianee**
this allow to preserve the display of childs, we don't know if it's block or inline block (or anything else)

### CODE REVIEW

**Comment by MrSaints** [comment]
Hey @lianee,

Thanks for the PR, and I love the use of the `:not` selector.

I'm mostly OK with this, but I'm just concerned about potential side-effects?

Right now, it seems like it causes a bit of jittering when used with default list elements (e.g. in `index.html`). Perhaps there needs to be some documentation on this (to inform people that extra styles may have to be applied).

**Comment by lianee** [comment]
Thanks for this cool utility

Strange, I just checked with the current index.html file in the Morphist folder, and don't see any glitch with current versions of FF, Chrome, Safari and Edge.

According to [caniuse](http://caniuse.com/#search=%3Anot), the not() selector is not supported in IE 7 and 8, no big surprise, but that should be mentioned of course, perhaps providing another css file for legacy browsers?

Can you tell me in which browser/setup you experience differences? this fiddle could be used as a base for tests: https://jsfiddle.net/0aky7L6o/

**Comment by MrSaints** [comment]
@lianee, I'm not too concerned about compatibility with anything < IE10 because this relies on CSS animations anyway. So ignoring legacy support is OK (unless someone voices their concern, but we can deal with that later).

I was on Chrome Version 52.0.2743.60 beta (64-bit), and I don't think it can be duplicated on JSFiddle. It's just a simple jumping scrollbar glitch. I believe it's because of the display, and width of the list items extending the page as they rotate. 

Thanks!

**Comment by lianee** [comment]
yes, I observed that scrollbar behavior on Edge, but also with the current css.

I just saw there was a ß3 branch, would you prefer I post PRs on that branch (Id have 2 more to suggest)?

**Comment by MrSaints** [comment]
Apologies for the delay in merging this @lianee.

I had a look again, and I couldn't find any major problems. I'm happy to have it merged on master :+1: 

For the time being, I'm OK with having PRs on master. That being said, I should merge ß3 soon (I can't remember why I've been holding it off). 

Thanks again! :smile:

**Pull request merged**
